### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by maximusblade** [DraperStudio/Laravel-Likeable#1]
Nice to have:

- List all users (by their like counts, asc desc)

**Comment by DraperStudio** [comment]
You could just call the `likes` method and query the users that way.

Might add a users method one day, but not for now.

**Comment by mbwatson** [comment]
This works to retrieve all the likers of a post

```
class Post extends Model implements Likeable
{
  use LikeableTrait;
  //...
  public function likers()
  {
    return User::whereIn('id', $this->likes()->lists('liked_by_id'));
  }
}
```

Then you can say

```
@foreach ($post->likers()->get() as $user)
    <a href="{{ route('users.show', $user) }}">{{ $user->name }}</a>
@endforeach
```

Is there a better way?
